export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS";
export const ALTERAR_PROJETO = "ALTERAR_PROJETO";
export const REMOVER_PROJETO = "REMOVER_PROJETO";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const CADASTRAR_TAREFAS = "CADASTRAR_TAREFAS";
export const ALTERAR_TAREFA = "ALTERAR_TAREFA";
export const REMOVER_TAREFA = "REMOVER_TAREFA";

export const LOGIN = "LOGIN";
export const GET_TOKEN = "GET_TOKEN";
export const GET_FIRST_ACCESS = "GET_FIRST_ACCESS";
export const LOGOUT = "LOGOUT";
export const REGISTER_USER = "REGISTER_USER";
export const REMOVE_FIRST_ACCESS = "REMOVE_FIRST_ACCESS";
export const GENERATE_DATA = "GENERATE_DATA";

export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";